

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: mandisync_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mandisync_password
      POSTGRES_DB: mandisync_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
